[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# This defines the workflow-builder service only
# For complete n8n stack deployment, use railway-template-postgres.json or railway-template.json
[services.n8n-workflow-builder]
source = "."