# Railway Template Configuration
# This file is used by Railway to create one-click deployment templates

name = "N8N Complete Automation Stack"
description = "Complete n8n automation stack with workflow builder, MySQL database, and n8n server for AI assistant integration"

[variables]
N8N_ADMIN_USER = { description = "Admin username for n8n", default = "admin" }
N8N_ADMIN_PASSWORD = { description = "Admin password for n8n (min 8 chars)", default = "" }
MYSQL_PASSWORD = { description = "MySQL password for n8n user", default = "" }
N8N_API_KEY = { description = "N8N API key (generate after deployment)", default = "", required = false }

[services.mysql]
source = "mysql:8.0"
variables = { 
  MYSQL_ROOT_PASSWORD = "root_${RAILWAY_ENVIRONMENT_ID}",
  MYSQL_DATABASE = "n8n",
  MYSQL_USER = "n8n",
  MYSQL_PASSWORD = "${MYSQL_PASSWORD}"
}

[services.n8n]
source = "n8nio/n8n:latest"
variables = {
  N8N_BASIC_AUTH_ACTIVE = "true",
  N8N_BASIC_AUTH_USER = "${N8N_ADMIN_USER}",
  N8N_BASIC_AUTH_PASSWORD = "${N8N_ADMIN_PASSWORD}",
  DB_TYPE = "mysqldb",
  DB_MYSQLDB_HOST = "${mysql.RAILWAY_PRIVATE_DOMAIN}",
  DB_MYSQLDB_PORT = "3306", 
  DB_MYSQLDB_DATABASE = "n8n",
  DB_MYSQLDB_USER = "n8n",
  DB_MYSQLDB_PASSWORD = "${MYSQL_PASSWORD}",
  N8N_HOST = "${RAILWAY_PUBLIC_DOMAIN}",
  WEBHOOK_URL = "${RAILWAY_PUBLIC_DOMAIN}",
  GENERIC_TIMEZONE = "UTC"
}
depends_on = ["mysql"]

[services.workflow-builder]
source = "."
variables = {
  USE_HTTP = "true",
  N8N_HOST = "${n8n.RAILWAY_PUBLIC_DOMAIN}",
  N8N_API_KEY = "${N8N_API_KEY}"
}
depends_on = ["n8n"]